### ISSUE TITLE
Mixed Content Blocking

### ISSUE THREAD

**Issue by omegalink12** [Ao-san/Ao-san.github.io#1]
The validation step sends a XMLHttpRequest to insecure endpoints. This will be automatically blocked by webbrowsers.

**Comment by Ao-san** [comment]
Replicate error and supply logs?

Mixed requests between http and ssl yield warnings in the majority of modern browsers, so this shouldn't be a problem.

**Comment by omegalink12** [comment]
![image](https://cloud.githubusercontent.com/assets/12601948/20330563/c0ca74cc-ab6d-11e6-82d3-1700912f22a2.png)
Load the page in chrome and open devtools

**Comment by Ao-san** [comment]
Works in Chrome for me, but fixed anyway since warning are annoying.

/thread
